[[ecosystem-plugin]]
= Java ecosystem capabilities resolution plugin

== Apply the plugin

[source,groovy]
----
plugins {
    id("org.gradlex.java-ecosystem-capabilities") version "2.0"
}
----

This plugin should be applied to all projects, ideally as part of your convention plugin.

The plugin will verify that the rules from the <<base.adoc#base-plugin,base plugin>> are available either through the central declaration mechanism or through the project's own rules.

== What is the concrete effect of the plugin?

The plugin registers capability conflict resolutions for the <<rules.adoc#capability-rules,capability rules>> added by the base plugin.
This enables a number of <<base.adoc#conflict,capability conflicts>> to be resolved automatically.

== Deactivating the default resolution strategy for capabilities

The plugin adds a _default resolution strategy_ for each capability.
Which in most cases means that Gradle will automatically pick the highest version of all components in conflict.
This is to cover the cases where users _just want things to work somehow_.
But it might not always be the right solution.

If you prefer to get all the conflicts reported and then add the conflict resolution explicitly (see next section),
you can deactivate the default resolution for one or all rules through the `javaEcosystemCapabilities` extension.

[source.multi-language-sample,kotlin]
----
// Deactivate default resolution strategy for all rules
javaEcosystemCapabilities {
    deactivatedResolutionStrategies.addAll(allCapabilities)
}

// Deactivate default resolution strategy for selected rules
javaEcosystemCapabilities {
    deactivatedResolutionStrategies.addAll(CGlibRule.CAPABILITY)
    deactivatedResolutionStrategies.addAll(JavaxMailApiRule.CAPABILITY)
}
----
[source.multi-language-sample,groovy]
----
// Deactivate default resolution strategy for all rules
javaEcosystemCapabilities {
    deactivatedResolutionStrategies.addAll(allCapabilities)
}

// Deactivate default resolution strategy for selected rules
javaEcosystemCapabilities {
    deactivatedResolutionStrategies.addAll(CGlibRule.CAPABILITY)
    deactivatedResolutionStrategies.addAll(JavaxMailApiRule.CAPABILITY)
}
----
