[[resolution-plugin]]
= JVM Ecosystem Conflict Resolution

== Plugin dependency
Add this to the build file of your convention plugin's build (e.g. `build-logic/build.gradle(.kts)` or `buildSrc/build.gradle(.kts)`).

[source,groovy]
----
dependencies {
    implementation("org.gradlex:jvm-ecosystem-conflict-resolution:2.0")
}
----

== Apply the plugin

[source,groovy]
----
plugins {
    id("org.gradlex.jvm-ecosystem-conflict-resolution")
}
----

This plugin should be applied to all projects, ideally as part of your convention plugin.

If the <<detection-plugin,jvm-ecosystem-conflict-resolution>> plugin has been explicitly applied as well, either as a settings or project plugin, it will be automatically applied (as project plugin).

== What is the concrete effect of the plugin?

The plugin registers capability conflict resolutions for the <<rules.adoc#capability-rules,capability rules>> added by the base plugin.
This enables a number of <<conflict,capability conflicts>> to be resolved automatically.
For conflicts that...

- cannot be resolved automatically
- should be resolved differently (than the default)
- are not detected correctly due to incomplete metadata

...this plugin offers the `jvmDependencyConflicts` DLS with the following sections.

[source,groovy]
----
jvmDependencyConflicts {
    conflictResolution {
        // Customize resolutin of capability conflicts
        select(JAVAX_ACTIVATION_API, "com.sun.activation:jakarta.activation")
    }

    logging {
        // Customize resolution of conflicts for a certain logging setup
        enforceSlf4JSimple()
    }

    patch {
        // Patch or extend wrong metdata
        module("com.googlecode.json-simple:json-simple") { removeDependency("junit:junit") }
    }
}
----

[[conflictResolution-dsl-block]]
== conflictResolution – Customize resolution strategies for capability conflicts

The plugin adds a _default resolution strategy_ for each capability.
Which in most cases means that Gradle will automatically pick the highest version of all components in conflict.
This is to cover the cases where users _just want things to work somehow_.
But it might not always be the right solution.

If you prefer to get all the conflicts reported and then add the conflict resolution explicitly (see next section),
you can deactivate the default resolution for one or all rules through the `jvmDependencyConflicts` extension.

[source.multi-language-sample,kotlin]
----
// Deactivate default resolution strategy for selected rules
jvmDependencyConflicts {
    conflictResolution {
        deactivateResolutionStrategy(CapabilityDefinitions.CGLIB)
        deactivateResolutionStrategy(CapabilityDefinitions.JAVAX_MAIL_API)
    }
}
----
[source.multi-language-sample,groovy]
----
// Deactivate default resolution strategy for selected rules
jvmDependencyConflicts {
    conflictResolution {
        deactivateResolutionStrategy(CapabilityDefinitions.CGLIB)
        deactivateResolutionStrategy(CapabilityDefinitions.JAVAX_MAIL_API)
    }
}
----

*TODO document more*

[[logging-dsl-block]]
== logging – Select and enforce a logging framework

This part of the DSL enables you to declaratively enforce the logging framework it your application should use _at build time_.

TIP: The different configuration options documented below do not _add_ dependencies.
Make sure to have the expected dependency in your graph, either as a direct or transitive one.

The `logging { }` block first provides a number of high-level, one stop solutions, for selecting a logging solution:

|===
| Method | Documentation | Required dependency

| `enforceLogback()` +
`enforceLogback(String configurationName)`
| This will configure all capabilities to resolve in favour of http://logback.qos.ch/[LOGBack] and route all alternative logging solutions through Slf4J.
| `ch.qos.logback:logback-classic`

| `enforceLog4J2()` +
`enforceLog4J2(String configurationName)`
| This will configure all capabilities to resolve in favour of http://logging.apache.org/log4j/2.x/[Log4J 2] and route all alternative logging solutions through Log4J 2.
| `org.apache.logging.log4j:log4j-slf4j-impl`

| `enforceSlf4JSimple()` +
`enforceSlf4JSimple(String configurationName)`
| This will configure all capabilities to resolve in favour of Slf4J simple and route all alternative logging solutions through Slf4J.
| `org.slf4j:slf4j-simple`

|===

TIP: The method without parameter will apply the setup to all dependency configuration, while the other one will limit the setup to the specified dependency configuration.

If you want a finer grained control, the `logging { }` block provides lower level entry points for solving the different logging capability conflicts:
|===
| Method | Accepted parameter values | Documentation

| `selectSlf4JBinding(Object notation)`
| Value must be an Slf4J binding implementation known by the plugin: `org.slf4j:slf4j-simple`, `org.slf4j:slf4j-log4j12`, `org.slf4j:slf4j-jcl`, `org.slf4j:slf4j-jdk14`, `ch.qos.logback:logback-classic` or `org.apache.logging.log4j:log4j-slf4j-impl`
| Configures the provided Slf4J binding for selection, configuring related capabilities if needed

| `selectSlf4JBinding(String configurationName, Object notation)`
| A dependency configuration name, that `canBeResolved=true` +
A notation as above
| Configures the provided Slf4J binding for selection, configuring related capabilities if needed, only for the provided dependency configuration

| `selectLog4J12Implementation(Object notation)`
| Value must be a Log4J 1.2 implementation known by the plugin: `org.slf4j:log4j-over-slf4j`, `org.apache.logging.log4j:log4j-1.2-api`, `log4:log4j` or `org.slf4j:slf4j-log4j12`
| Configures the provided Log4J 1.2 implementation for selection, configuring related capabilities if needed

| `selectLog4J12Implementation(String configurationName, Object notation)`
| A dependency configuration name, that `canBeResolved=true` +
A notation as above
| Configures the provided Log4J 1.2 implementation for selection, configuring related capabilities if needed, only for the provided dependency configuration

| `selectJulDelegation(Object notation)`
| Value must be a `java.util.logging` interceptor or binding known by the plugin: `org.slf4j:jul-to-slf4j`, `org.slf4j:slf4j-jdk14` or `org.apache.logging.log4j:log4j-jul`
| Configures the provided JUL integration of binding for selection, configuring related capabilities if needed

| `selectJulDelegation(String configurationName, Object notation)`
| A dependency configuration name, that `canBeResolved=true` +
A notation as above
| Configures the provided JUL integration for selection, configuring related capabilities if needed, only for the provided dependency configuration

| `selectJCLImplementation(Object notation)`
| Value must be a Apache Commons Logging interceptor or binding known by the plugin: `org.slf4j:jcl-over-slf4j`, `commons-logging:commons-logging`, `org.slf4j:slf4j-jcl` or `org.apache.logging.log4j:log4j-jcl`
| Configures the provided commons logging interceptor or binding for selection, configuring related capabilities if needed

| `selectJCLImplementation(String configurationName, Object notation)`
| A dependency configuration name, that `canBeResolved=true` +
A notation as above
| Configures the provided commons logging interceptor or binding for selection, configuring related capabilities if needed, only for the provided dependency configuration

| `selectSlf4JLog4J2Interaction(Object notation)`
| Value must be a Log4J 2 module for Slf4J interaction known by the plugin: `org.apache.logging.log4j:log4j-to-slf4j` or `org.apache.logging.log4j:log4j-slf4j-impl`
| Configures the Log4J 2 / Slf4J integration, configuring related capabilities if needed

| `selectSlf4JLog4J2Interaction(Sting configurationName, Object notation)`
| A dependency configuration name, that `canBeResolved=true` +
A notation as above
| Configures the Log4J 2 / Slf4J integration, configuring related capabilities if needed, only for the provided dependency configuration

|===

TIP: Notations above are those accepted by https://docs.gradle.org/6.0.1/dsl/org.gradle.api.artifacts.dsl.DependencyHandler.html#org.gradle.api.artifacts.dsl.DependencyHandler:create(java.lang.Object)[`DependencyHandler.create(notation)`] in Gradle that resolves to an `ExternalDependency`.
Most often this is a `group:name:version` `String`.

[[patch-dsl-block]]
== patch – Patch metadata of published components

*TODO document*